/**
 * Standalone seed script.
 *   Run once with:  node server/seed/seedRecipes.js
 * Populates the Recipe collection with 25 realistic sample recipes so the
 * matching feature has real data to demo immediately.
 */
require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Recipe = require('../models/Recipe');

const img = (q) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=800&q=70`;

const recipes = [
  {
    title: 'Classic Margherita Pizza',
    description: 'A simple Neapolitan-style pizza with tomatoes, mozzarella, and fresh basil.',
    cuisine: 'Italian',
    dietaryTags: ['vegetarian'],
    prepTime: 20,
    cookTime: 12,
    servings: 2,
    difficulty: 'medium',
    imageUrl: img('photo-1513104890138-7c749659a591'),
    ingredients: [
      { name: 'pizza dough', quantity: '1', unit: 'ball' },
      { name: 'tomatoes', quantity: '400', unit: 'g' },
      { name: 'mozzarella', quantity: '200', unit: 'g' },
      { name: 'basil', quantity: '8', unit: 'leaves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    instructions: [
      'Preheat the oven to its highest setting with a baking stone or tray inside.',
      'Stretch the pizza dough into a thin round on a floured surface.',
      'Spread crushed tomatoes over the base, leaving a border for the crust.',
      'Tear the mozzarella and scatter it over the tomatoes.',
      'Bake for 10 to 12 minutes until the crust is blistered and golden.',
      'Finish with fresh basil, a drizzle of olive oil, and a pinch of salt.',
    ],
  },
  {
    title: 'Spaghetti Aglio e Olio',
    description: 'Garlicky, peppery spaghetti that comes together in minutes.',
    cuisine: 'Italian',
    dietaryTags: ['vegetarian', 'vegan'],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: 'easy',
    imageUrl: img('photo-1551892374-ecf8754cf8b0'),
    ingredients: [
      { name: 'spaghetti', quantity: '200', unit: 'g' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'olive oil', quantity: '4', unit: 'tbsp' },
      { name: 'chili flakes', quantity: '1', unit: 'tsp' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Cook the spaghetti in salted boiling water until al dente.',
      'Gently warm sliced garlic and chili flakes in olive oil until fragrant.',
      'Toss the drained pasta in the garlic oil with a splash of pasta water.',
      'Stir through chopped parsley and serve immediately.',
    ],
  },
  {
    title: 'Chicken Tikka Masala',
    description: 'Tender chicken in a creamy, spiced tomato sauce.',
    cuisine: 'Indian',
    dietaryTags: ['gluten-free'],
    prepTime: 25,
    cookTime: 30,
    servings: 4,
    difficulty: 'medium',
    imageUrl: img('photo-1565557623262-b51c2513a641'),
    ingredients: [
      { name: 'chicken breast', quantity: '600', unit: 'g' },
      { name: 'yogurt', quantity: '150', unit: 'g' },
      { name: 'tomatoes', quantity: '400', unit: 'g' },
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tbsp' },
      { name: 'cream', quantity: '100', unit: 'ml' },
      { name: 'garam masala', quantity: '2', unit: 'tsp' },
    ],
    instructions: [
      'Marinate the diced chicken in yogurt and half the spices for 20 minutes.',
      'Sear the chicken in a hot pan until charred at the edges, then set aside.',
      'Soften the onion, garlic, and ginger, then add the remaining spices.',
      'Pour in the tomatoes and simmer until thickened.',
      'Return the chicken, stir in the cream, and simmer until cooked through.',
    ],
  },
  {
    title: 'Vegetable Fried Rice',
    description: 'A quick weeknight stir-fry that rescues leftover rice.',
    cuisine: 'Chinese',
    dietaryTags: ['vegetarian'],
    prepTime: 10,
    cookTime: 10,
    servings: 3,
    difficulty: 'easy',
    imageUrl: img('photo-1603133872878-684f208fb84b'),
    ingredients: [
      { name: 'rice', quantity: '3', unit: 'cups' },
      { name: 'eggs', quantity: '2', unit: '' },
      { name: 'carrot', quantity: '1', unit: '' },
      { name: 'peas', quantity: '100', unit: 'g' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'spring onion', quantity: '2', unit: '' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
    ],
    instructions: [
      'Scramble the eggs in a hot wok and set aside.',
      'Stir-fry the garlic, diced carrot, and peas until just tender.',
      'Add the cold rice and toss over high heat to separate the grains.',
      'Return the eggs, add soy sauce, and finish with sliced spring onion.',
    ],
  },
  {
    title: 'Beef Tacos',
    description: 'Seasoned beef in warm tortillas with fresh toppings.',
    cuisine: 'Mexican',
    dietaryTags: [],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'easy',
    imageUrl: img('photo-1565299585323-38d6b0865b47'),
    ingredients: [
      { name: 'ground beef', quantity: '500', unit: 'g' },
      { name: 'tortillas', quantity: '8', unit: '' },
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'tomatoes', quantity: '2', unit: '' },
      { name: 'cheese', quantity: '100', unit: 'g' },
      { name: 'cumin', quantity: '1', unit: 'tbsp' },
      { name: 'lettuce', quantity: '1', unit: 'cup' },
    ],
    instructions: [
      'Brown the ground beef with chopped onion until cooked through.',
      'Stir in cumin and a splash of water; simmer to coat the meat.',
      'Warm the tortillas in a dry pan.',
      'Fill with beef, then top with tomatoes, lettuce, and cheese.',
    ],
  },
  {
    title: 'Greek Salad',
    description: 'Crisp vegetables, olives, and feta with a lemon-oregano dressing.',
    cuisine: 'Greek',
    dietaryTags: ['vegetarian', 'gluten-free'],
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    difficulty: 'easy',
    imageUrl: img('photo-1540420773420-3366772f4999'),
    ingredients: [
      { name: 'cucumber', quantity: '1', unit: '' },
      { name: 'tomatoes', quantity: '3', unit: '' },
      { name: 'red onion', quantity: '0.5', unit: '' },
      { name: 'feta', quantity: '150', unit: 'g' },
      { name: 'olives', quantity: '50', unit: 'g' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
    ],
    instructions: [
      'Chop the cucumber and tomatoes into chunks and thinly slice the onion.',
      'Combine in a bowl with the olives.',
      'Top with a block of feta and sprinkle with oregano.',
      'Dress with olive oil and a squeeze of lemon just before serving.',
    ],
  },
  {
    title: 'Thai Green Curry',
    description: 'Fragrant coconut curry with vegetables and chicken.',
    cuisine: 'Thai',
    dietaryTags: ['gluten-free'],
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    difficulty: 'medium',
    imageUrl: img('photo-1455619452474-d2be8b1e70cd'),
    ingredients: [
      { name: 'chicken thigh', quantity: '500', unit: 'g' },
      { name: 'green curry paste', quantity: '3', unit: 'tbsp' },
      { name: 'coconut milk', quantity: '400', unit: 'ml' },
      { name: 'bell pepper', quantity: '1', unit: '' },
      { name: 'bamboo shoots', quantity: '100', unit: 'g' },
      { name: 'fish sauce', quantity: '1', unit: 'tbsp' },
      { name: 'basil', quantity: '1', unit: 'handful' },
    ],
    instructions: [
      'Fry the curry paste in a little oil until aromatic.',
      'Add the sliced chicken and brown lightly.',
      'Pour in the coconut milk and bring to a gentle simmer.',
      'Add the pepper and bamboo shoots; cook until tender.',
      'Season with fish sauce and finish with torn basil.',
    ],
  },
  {
    title: 'Pancakes',
    description: 'Fluffy breakfast pancakes ready for your favorite toppings.',
    cuisine: 'American',
    dietaryTags: ['vegetarian'],
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    difficulty: 'easy',
    imageUrl: img('photo-1567620905732-2d1ec7ab7445'),
    ingredients: [
      { name: 'flour', quantity: '200', unit: 'g' },
      { name: 'milk', quantity: '300', unit: 'ml' },
      { name: 'eggs', quantity: '2', unit: '' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'baking powder', quantity: '2', unit: 'tsp' },
      { name: 'butter', quantity: '30', unit: 'g' },
    ],
    instructions: [
      'Whisk together the flour, sugar, and baking powder.',
      'Beat in the eggs and milk until you have a smooth batter.',
      'Melt a little butter in a pan over medium heat.',
      'Pour in batter and cook until bubbles form, then flip and finish.',
    ],
  },
  {
    title: 'Caprese Avocado Toast',
    description: 'Sourdough toast layered with avocado, tomato, and mozzarella.',
    cuisine: 'American',
    dietaryTags: ['vegetarian'],
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    difficulty: 'easy',
    imageUrl: img('photo-1525351484163-7529414344d8'),
    ingredients: [
      { name: 'bread', quantity: '2', unit: 'slices' },
      { name: 'avocado', quantity: '1', unit: '' },
      { name: 'tomatoes', quantity: '1', unit: '' },
      { name: 'mozzarella', quantity: '80', unit: 'g' },
      { name: 'basil', quantity: '6', unit: 'leaves' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Toast the bread until golden and crisp.',
      'Mash the avocado with a pinch of salt and spread over the toast.',
      'Layer with sliced tomato and mozzarella.',
      'Top with basil and a drizzle of olive oil.',
    ],
  },
  {
    title: 'Miso Ramen',
    description: 'A comforting bowl of noodles in a savory miso broth.',
    cuisine: 'Japanese',
    dietaryTags: [],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: 'medium',
    imageUrl: img('photo-1569718212165-3a8278d5f624'),
    ingredients: [
      { name: 'ramen noodles', quantity: '2', unit: 'portions' },
      { name: 'miso paste', quantity: '3', unit: 'tbsp' },
      { name: 'eggs', quantity: '2', unit: '' },
      { name: 'spring onion', quantity: '2', unit: '' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'corn', quantity: '50', unit: 'g' },
    ],
    instructions: [
      'Soft-boil the eggs for 6.5 minutes, then peel and halve.',
      'Sauté the garlic and ginger, then whisk in miso and stock.',
      'Add soy sauce and bring the broth to a gentle simmer.',
      'Cook the noodles separately and divide between bowls.',
      'Ladle over the broth and top with egg, corn, and spring onion.',
    ],
  },
  {
    title: 'Hummus from Scratch',
    description: 'Silky smooth chickpea dip with tahini and lemon.',
    cuisine: 'Middle Eastern',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: 'easy',
    imageUrl: img('photo-1601000938259-9e92002320b2'),
    ingredients: [
      { name: 'chickpeas', quantity: '400', unit: 'g' },
      { name: 'tahini', quantity: '3', unit: 'tbsp' },
      { name: 'lemon', quantity: '1', unit: '' },
      { name: 'garlic', quantity: '1', unit: 'clove' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
    ],
    instructions: [
      'Drain the chickpeas, reserving a little of the liquid.',
      'Blend the chickpeas with tahini, lemon juice, and garlic.',
      'Loosen with the reserved liquid until smooth and creamy.',
      'Finish with olive oil and a dusting of paprika.',
    ],
  },
  {
    title: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato and pepper sauce.',
    cuisine: 'Middle Eastern',
    dietaryTags: ['vegetarian', 'gluten-free'],
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    difficulty: 'easy',
    imageUrl: img('photo-1590412200988-a436970781fa'),
    ingredients: [
      { name: 'eggs', quantity: '4', unit: '' },
      { name: 'tomatoes', quantity: '400', unit: 'g' },
      { name: 'bell pepper', quantity: '1', unit: '' },
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'paprika', quantity: '1', unit: 'tsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
    ],
    instructions: [
      'Soften the onion and pepper in oil until sweet.',
      'Add garlic, paprika, and cumin and cook for a minute.',
      'Pour in the tomatoes and simmer until thickened.',
      'Make wells in the sauce and crack in the eggs.',
      'Cover and cook until the whites are just set.',
    ],
  },
  {
    title: 'Beef Stir-Fry with Broccoli',
    description: 'Quick savory beef and broccoli in a glossy sauce.',
    cuisine: 'Chinese',
    dietaryTags: [],
    prepTime: 15,
    cookTime: 10,
    servings: 3,
    difficulty: 'easy',
    imageUrl: img('photo-1512058564366-18510be2db19'),
    ingredients: [
      { name: 'beef strips', quantity: '400', unit: 'g' },
      { name: 'broccoli', quantity: '1', unit: 'head' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tbsp' },
      { name: 'cornstarch', quantity: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Toss the beef with cornstarch and a splash of soy sauce.',
      'Sear the beef in a hot wok until browned, then remove.',
      'Stir-fry the broccoli with garlic and ginger until bright green.',
      'Return the beef, add the rest of the soy sauce, and toss to glaze.',
    ],
  },
  {
    title: 'Lentil Soup',
    description: 'Hearty, warming lentil soup with vegetables.',
    cuisine: 'Mediterranean',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    difficulty: 'easy',
    imageUrl: img('photo-1547592180-85f173990554'),
    ingredients: [
      { name: 'lentils', quantity: '250', unit: 'g' },
      { name: 'carrot', quantity: '2', unit: '' },
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'celery', quantity: '2', unit: 'stalks' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'vegetable stock', quantity: '1', unit: 'liter' },
    ],
    instructions: [
      'Sweat the chopped onion, carrot, and celery until soft.',
      'Add the garlic and cumin and cook briefly.',
      'Stir in the lentils and stock and bring to a boil.',
      'Simmer for 30 minutes until the lentils are tender.',
      'Blend partially for a thicker texture if you like.',
    ],
  },
  {
    title: 'Caesar Salad',
    description: 'Crisp romaine with a creamy dressing and croutons.',
    cuisine: 'American',
    dietaryTags: [],
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    difficulty: 'easy',
    imageUrl: img('photo-1550304943-4f24f54ddde9'),
    ingredients: [
      { name: 'romaine lettuce', quantity: '1', unit: 'head' },
      { name: 'bread', quantity: '2', unit: 'slices' },
      { name: 'parmesan', quantity: '40', unit: 'g' },
      { name: 'mayonnaise', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '1', unit: 'clove' },
      { name: 'lemon', quantity: '0.5', unit: '' },
    ],
    instructions: [
      'Cube the bread and toast in oil until crunchy to make croutons.',
      'Whisk mayonnaise with grated garlic, lemon, and half the parmesan.',
      'Toss the torn romaine with the dressing.',
      'Top with croutons and the remaining parmesan.',
    ],
  },
  {
    title: 'Mushroom Risotto',
    description: 'Creamy Arborio rice with earthy mushrooms.',
    cuisine: 'Italian',
    dietaryTags: ['vegetarian', 'gluten-free'],
    prepTime: 10,
    cookTime: 30,
    servings: 3,
    difficulty: 'medium',
    imageUrl: img('photo-1476124369491-e7addf5db371'),
    ingredients: [
      { name: 'arborio rice', quantity: '300', unit: 'g' },
      { name: 'mushrooms', quantity: '250', unit: 'g' },
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'parmesan', quantity: '50', unit: 'g' },
      { name: 'vegetable stock', quantity: '1', unit: 'liter' },
      { name: 'butter', quantity: '30', unit: 'g' },
    ],
    instructions: [
      'Sauté the mushrooms until golden and set aside.',
      'Soften the onion and garlic, then toast the rice for a minute.',
      'Add the warm stock a ladle at a time, stirring until absorbed.',
      'When the rice is creamy and tender, stir in the mushrooms.',
      'Finish with butter and parmesan off the heat.',
    ],
  },
  {
    title: 'Falafel Wrap',
    description: 'Crispy spiced chickpea fritters in a soft flatbread.',
    cuisine: 'Middle Eastern',
    dietaryTags: ['vegetarian', 'vegan'],
    prepTime: 20,
    cookTime: 15,
    servings: 3,
    difficulty: 'medium',
    imageUrl: img('photo-1593001874117-c99c800e3eb7'),
    ingredients: [
      { name: 'chickpeas', quantity: '400', unit: 'g' },
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'parsley', quantity: '1', unit: 'bunch' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'flatbread', quantity: '3', unit: '' },
      { name: 'tahini', quantity: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Blend chickpeas with onion, garlic, parsley, and cumin into a coarse paste.',
      'Shape into small patties and chill briefly.',
      'Shallow-fry until deeply golden and crisp.',
      'Warm the flatbread and fill with falafel and a drizzle of tahini.',
    ],
  },
  {
    title: 'Banana Oat Smoothie',
    description: 'A filling breakfast smoothie with banana and oats.',
    cuisine: 'American',
    dietaryTags: ['vegetarian', 'gluten-free'],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: 'easy',
    imageUrl: img('photo-1553530666-ba11a7da3888'),
    ingredients: [
      { name: 'banana', quantity: '1', unit: '' },
      { name: 'oats', quantity: '40', unit: 'g' },
      { name: 'milk', quantity: '250', unit: 'ml' },
      { name: 'honey', quantity: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Add the banana, oats, milk, and honey to a blender.',
      'Blend until completely smooth.',
      'Pour into a glass and serve cold.',
    ],
  },
  {
    title: 'Egg Fried Noodles',
    description: 'Speedy noodles tossed with egg and vegetables.',
    cuisine: 'Chinese',
    dietaryTags: ['vegetarian'],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: 'easy',
    imageUrl: img('photo-1585032226651-759b368d7246'),
    ingredients: [
      { name: 'noodles', quantity: '200', unit: 'g' },
      { name: 'eggs', quantity: '2', unit: '' },
      { name: 'cabbage', quantity: '150', unit: 'g' },
      { name: 'carrot', quantity: '1', unit: '' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'spring onion', quantity: '2', unit: '' },
    ],
    instructions: [
      'Cook the noodles, drain, and toss with a little oil.',
      'Scramble the eggs in a hot wok and push to one side.',
      'Stir-fry the shredded cabbage and carrot until softened.',
      'Add the noodles and soy sauce and toss everything together.',
      'Finish with sliced spring onion.',
    ],
  },
  {
    title: 'Tomato Basil Soup',
    description: 'Smooth, comforting tomato soup with fresh basil.',
    cuisine: 'Mediterranean',
    dietaryTags: ['vegetarian', 'gluten-free'],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: 'easy',
    imageUrl: img('photo-1547592166-23ac45744acd'),
    ingredients: [
      { name: 'tomatoes', quantity: '800', unit: 'g' },
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'basil', quantity: '1', unit: 'handful' },
      { name: 'vegetable stock', quantity: '500', unit: 'ml' },
      { name: 'cream', quantity: '50', unit: 'ml' },
    ],
    instructions: [
      'Soften the onion and garlic in a little oil.',
      'Add the tomatoes and stock and simmer for 20 minutes.',
      'Blend until smooth and stir in the basil.',
      'Swirl in a little cream before serving.',
    ],
  },
  {
    title: 'Honey Garlic Salmon',
    description: 'Pan-seared salmon glazed in a sweet and savory sauce.',
    cuisine: 'American',
    dietaryTags: ['gluten-free'],
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    difficulty: 'easy',
    imageUrl: img('photo-1467003909585-2f8a72700288'),
    ingredients: [
      { name: 'salmon fillet', quantity: '2', unit: '' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'lemon', quantity: '0.5', unit: '' },
      { name: 'butter', quantity: '20', unit: 'g' },
    ],
    instructions: [
      'Sear the salmon skin-side down until crisp, then flip.',
      'Add the butter, garlic, honey, and soy sauce to the pan.',
      'Spoon the bubbling glaze over the salmon as it finishes cooking.',
      'Squeeze over lemon and serve.',
    ],
  },
  {
    title: 'Veggie Quesadilla',
    description: 'Golden tortillas filled with melted cheese and peppers.',
    cuisine: 'Mexican',
    dietaryTags: ['vegetarian'],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: 'easy',
    imageUrl: img('photo-1618040996337-56904b7850b9'),
    ingredients: [
      { name: 'tortillas', quantity: '4', unit: '' },
      { name: 'cheese', quantity: '150', unit: 'g' },
      { name: 'bell pepper', quantity: '1', unit: '' },
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'beans', quantity: '200', unit: 'g' },
    ],
    instructions: [
      'Sauté the sliced pepper and onion until soft.',
      'Lay a tortilla in a dry pan and scatter with cheese, beans, and veg.',
      'Top with a second tortilla and cook until golden.',
      'Flip carefully, melt the other side, then slice into wedges.',
    ],
  },
  {
    title: 'Chicken Caesar Wrap',
    description: 'Grilled chicken and crisp lettuce wrapped to go.',
    cuisine: 'American',
    dietaryTags: [],
    prepTime: 15,
    cookTime: 12,
    servings: 2,
    difficulty: 'easy',
    imageUrl: img('photo-1626700051175-6818013e1d4f'),
    ingredients: [
      { name: 'chicken breast', quantity: '2', unit: '' },
      { name: 'tortillas', quantity: '2', unit: '' },
      { name: 'romaine lettuce', quantity: '0.5', unit: 'head' },
      { name: 'parmesan', quantity: '30', unit: 'g' },
      { name: 'mayonnaise', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '1', unit: 'clove' },
    ],
    instructions: [
      'Season and grill the chicken, then slice it.',
      'Mix the mayonnaise with grated garlic and parmesan.',
      'Toss the lettuce in the dressing.',
      'Pile chicken and lettuce onto the tortillas and roll up tightly.',
    ],
  },
  {
    title: 'Vegan Buddha Bowl',
    description: 'A colorful bowl of grains, roasted veg, and tahini dressing.',
    cuisine: 'Mediterranean',
    dietaryTags: ['vegetarian', 'vegan', 'gluten-free'],
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    difficulty: 'medium',
    imageUrl: img('photo-1512621776951-a57141f2eefd'),
    ingredients: [
      { name: 'quinoa', quantity: '150', unit: 'g' },
      { name: 'sweet potato', quantity: '1', unit: '' },
      { name: 'chickpeas', quantity: '200', unit: 'g' },
      { name: 'spinach', quantity: '100', unit: 'g' },
      { name: 'avocado', quantity: '1', unit: '' },
      { name: 'tahini', quantity: '2', unit: 'tbsp' },
      { name: 'lemon', quantity: '0.5', unit: '' },
    ],
    instructions: [
      'Roast the cubed sweet potato and chickpeas until crisp.',
      'Cook the quinoa according to the package and fluff with a fork.',
      'Whisk tahini with lemon juice and water to make a dressing.',
      'Assemble the bowl with quinoa, roasted veg, spinach, and avocado.',
      'Drizzle generously with the tahini dressing.',
    ],
  },
  {
    title: 'Garlic Butter Shrimp Pasta',
    description: 'Succulent shrimp tossed with linguine in garlic butter.',
    cuisine: 'Italian',
    dietaryTags: [],
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    difficulty: 'medium',
    imageUrl: img('photo-1563379926898-05f4575a45d8'),
    ingredients: [
      { name: 'linguine', quantity: '250', unit: 'g' },
      { name: 'shrimp', quantity: '300', unit: 'g' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'butter', quantity: '40', unit: 'g' },
      { name: 'chili flakes', quantity: '0.5', unit: 'tsp' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
      { name: 'lemon', quantity: '0.5', unit: '' },
    ],
    instructions: [
      'Cook the linguine until al dente and reserve some pasta water.',
      'Melt the butter and gently cook the garlic and chili flakes.',
      'Add the shrimp and cook until just pink.',
      'Toss in the pasta with a splash of pasta water and lemon.',
      'Finish with chopped parsley.',
    ],
  },
];

async function seed() {
  await connectDB();
  try {
    const existing = await Recipe.countDocuments();
    console.log(`[seed] Found ${existing} existing recipes. Clearing collection...`);
    await Recipe.deleteMany({});
    const inserted = await Recipe.insertMany(recipes);
    console.log(`[seed] Inserted ${inserted.length} sample recipes.`);
  } catch (err) {
    console.error('[seed] Failed to seed recipes:', err.message);
    process.exitCode = 1;
  } finally {
    await mongoose.connection.close();
    console.log('[seed] Connection closed. Done.');
  }
}

seed();
